apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms
        image: krupa8/bms:latest
        ports:
        - containerPort: 3000
