apiVersion: v1
kind: Service
metadata:
  name: bms-service
  labels:
    app: bms
spec:
  selector:
    app: bms
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
